# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ratal/workspace/mdfreader/mdfreaderui.ui'
#
# Created: Tue Aug 23 22:37:57 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 600)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.Convert = QtGui.QPushButton(self.centralWidget)
        self.Convert.setGeometry(QtCore.QRect(690, 380, 97, 27))
        self.Convert.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.Convert.setObjectName("Convert")
        self.browse = QtGui.QPushButton(self.centralWidget)
        self.browse.setGeometry(QtCore.QRect(690, 20, 101, 31))
        self.browse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.browse.setAutoDefault(False)
        self.browse.setDefault(False)
        self.browse.setObjectName("browse")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(480, 0, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.label_3.setObjectName("label_3")
        self.splitter_3 = QtGui.QSplitter(self.centralWidget)
        self.splitter_3.setGeometry(QtCore.QRect(690, 60, 116, 291))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtGui.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ConvertSelect = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.ConvertSelect.setObjectName("ConvertSelect")
        self.matlab = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.matlab.setEnabled(True)
        self.matlab.setChecked(True)
        self.matlab.setObjectName("matlab")
        self.ConvertSelect.addWidget(self.matlab)
        self.netcdf = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.netcdf.setObjectName("netcdf")
        self.ConvertSelect.addWidget(self.netcdf)
        self.hdf5 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.hdf5.setObjectName("hdf5")
        self.ConvertSelect.addWidget(self.hdf5)
        self.csv = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.csv.setObjectName("csv")
        self.ConvertSelect.addWidget(self.csv)
        self.excel = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.excel.setObjectName("excel")
        self.ConvertSelect.addWidget(self.excel)
        self.horizontalLayoutWidget = QtGui.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Resample = QtGui.QVBoxLayout(self.horizontalLayoutWidget)
        self.Resample.setObjectName("Resample")
        self.resample = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.resample.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.resample.setObjectName("resample")
        self.Resample.addWidget(self.resample)
        self.resampleValue = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.resampleValue.setEnabled(True)
        self.resampleValue.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.resampleValue.setObjectName("resampleValue")
        self.Resample.addWidget(self.resampleValue)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.LabFile_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.LabFile_2.setObjectName("LabFile_2")
        self.LabFileBrowse = QtGui.QPushButton(self.layoutWidget)
        self.LabFileBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.LabFileBrowse.setObjectName("LabFileBrowse")
        self.LabFile_2.addWidget(self.LabFileBrowse)
        self.LabFile = QtGui.QLineEdit(self.layoutWidget)
        self.LabFile.setEnabled(True)
        self.LabFile.setObjectName("LabFile")
        self.LabFile_2.addWidget(self.LabFile)
        self.MergeFiles = QtGui.QCheckBox(self.splitter_3)
        self.MergeFiles.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.MergeFiles.setObjectName("MergeFiles")
        self.splitter_4 = QtGui.QSplitter(self.centralWidget)
        self.splitter_4.setGeometry(QtCore.QRect(10, 20, 681, 581))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.FileList = QtGui.QListWidget(self.splitter_4)
        self.FileList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.FileList.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.FileList.setAlternatingRowColors(True)
        self.FileList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.FileList.setProperty("isWrapping", True)
        self.FileList.setResizeMode(QtGui.QListView.Adjust)
        self.FileList.setObjectName("FileList")
        self.channelList = QtGui.QListWidget(self.splitter_4)
        self.channelList.setAcceptDrops(True)
        self.channelList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.channelList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.channelList.setDragEnabled(True)
        self.channelList.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.channelList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.channelList.setAlternatingRowColors(True)
        self.channelList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.channelList.setObjectName("channelList")
        self.SelectedChannelList = QtGui.QListWidget(self.splitter_4)
        self.SelectedChannelList.setAcceptDrops(True)
        self.SelectedChannelList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.SelectedChannelList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.SelectedChannelList.setDragEnabled(True)
        self.SelectedChannelList.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.SelectedChannelList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.SelectedChannelList.setAlternatingRowColors(True)
        self.SelectedChannelList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.SelectedChannelList.setObjectName("SelectedChannelList")
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionBrowse = QtGui.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.label.setBuddy(self.channelList)
        self.label_2.setBuddy(self.FileList)
        self.label_3.setBuddy(self.SelectedChannelList)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.resample, QtCore.SIGNAL("clicked()"), self.resampleValue.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MDF Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.Convert.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.browse.setToolTip(QtGui.QApplication.translate("MainWindow", "Click and select MDF file for conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.browse.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "File Channel List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "File List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Selected Channel List", None, QtGui.QApplication.UnicodeUTF8))
        self.matlab.setText(QtGui.QApplication.translate("MainWindow", "Matlab .mat", None, QtGui.QApplication.UnicodeUTF8))
        self.netcdf.setText(QtGui.QApplication.translate("MainWindow", "netCDF", None, QtGui.QApplication.UnicodeUTF8))
        self.hdf5.setText(QtGui.QApplication.translate("MainWindow", "HDF5", None, QtGui.QApplication.UnicodeUTF8))
        self.csv.setText(QtGui.QApplication.translate("MainWindow", "CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.excel.setText(QtGui.QApplication.translate("MainWindow", "Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.resample.setText(QtGui.QApplication.translate("MainWindow", "Resample", None, QtGui.QApplication.UnicodeUTF8))
        self.LabFileBrowse.setText(QtGui.QApplication.translate("MainWindow", "Lab file", None, QtGui.QApplication.UnicodeUTF8))
        self.MergeFiles.setText(QtGui.QApplication.translate("MainWindow", "MergeFiles", None, QtGui.QApplication.UnicodeUTF8))
        self.FileList.setSortingEnabled(True)
        self.channelList.setSortingEnabled(True)
        self.SelectedChannelList.setSortingEnabled(True)
        self.actionBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBrowse.setToolTip(QtGui.QApplication.translate("MainWindow", "Open MDF file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBrowse.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

